config/routes.rb
Rails.application.routes.draw do
  resources :pay_durations do
    member do
      put :position
    end
  end
  resources :payroll_calendars
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  
  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/payroll_calendar.rb
class PayrollCalendar < ApplicationRecord

  has_many :pay_durations, ->{ order(position: :asc) }, dependent: :destroy

  def payroll_periods
    
    date_ranges = []

    if pay_durations.count > 0
      
      i = 0
      range = pay_durations[i].range
      year = (starts_on..starts_on + 1.year - 1.day)

      while year.include?(range.begin)
        date_ranges << range
        i = (i + 1) % pay_durations.size
        range = pay_durations[i].range(after: date_ranges.last.end)
      end
      
    end
    
    date_ranges    
  end

end

app/controllers/payroll_calendars_controller.rb
class PayrollCalendarsController < ApplicationController
  before_action :set_payroll_calendar, only: %i[ show edit update destroy ]

  # GET /payroll_calendars or /payroll_calendars.json
  def index
    @payroll_calendars = PayrollCalendar.all
  end

  # GET /payroll_calendars/1 or /payroll_calendars/1.json
  def show
  end

  # GET /payroll_calendars/new
  def new
    @payroll_calendar = PayrollCalendar.new
  end

  # GET /payroll_calendars/1/edit
  def edit
  end

  # POST /payroll_calendars or /payroll_calendars.json
  def create
    @payroll_calendar = PayrollCalendar.new(payroll_calendar_params)

    respond_to do |format|
      if @payroll_calendar.save
        format.html { redirect_to payroll_calendar_url(@payroll_calendar), notice: "Payroll calendar was successfully created." }
        format.json { render :show, status: :created, location: @payroll_calendar }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @payroll_calendar.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /payroll_calendars/1 or /payroll_calendars/1.json
  def update
    respond_to do |format|
      if @payroll_calendar.update(payroll_calendar_params)
        format.html { redirect_to payroll_calendar_url(@payroll_calendar), notice: "Payroll calendar was successfully updated." }
        format.json { render :show, status: :ok, location: @payroll_calendar }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @payroll_calendar.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /payroll_calendars/1 or /payroll_calendars/1.json
  def destroy
    @payroll_calendar.destroy!

    respond_to do |format|
      format.html { redirect_to payroll_calendars_url, notice: "Payroll calendar was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_payroll_calendar
      @payroll_calendar = PayrollCalendar.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def payroll_calendar_params
      params.require(:payroll_calendar).permit(:starts_on)
    end
end

app/helpers/payroll_calendars_helper.rb
module PayrollCalendarsHelper
end

app/views/payroll_calendars/_form.html.erb
<%= form_with(model: payroll_calendar) do |form| %>
  <% if payroll_calendar.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(payroll_calendar.errors.count, "error") %> prohibited this payroll_calendar from being saved:</h2>

      <ul>
        <% payroll_calendar.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :starts_on, style: "display: block" %>
    <%= form.date_field :starts_on %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/payroll_calendars/_payroll_calendar.html.erb
<div id="<%= dom_id payroll_calendar %>">
  <p>
    <strong>Starts on:</strong>
    <%= payroll_calendar.starts_on %>
  </p>

</div>

app/views/payroll_calendars/edit.html.erb
<h1>Editing payroll calendar</h1>

<%= render "form", payroll_calendar: @payroll_calendar %>

<br>

<div>
  <%= link_to "Show this payroll calendar", @payroll_calendar %> |
  <%= link_to "Back to payroll calendars", payroll_calendars_path %>
</div>

app/views/payroll_calendars/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Payroll calendars</h1>

<div id="payroll_calendars">
  <% @payroll_calendars.each do |payroll_calendar| %>
    <%= render payroll_calendar %>
    <p>
      <%= link_to "Show this payroll calendar", payroll_calendar %>
    </p>
  <% end %>
</div>

<%= link_to "New payroll calendar", new_payroll_calendar_path %>

app/views/payroll_calendars/new.html.erb
<h1>New payroll calendar</h1>

<%= render "form", payroll_calendar: @payroll_calendar %>

<br>

<div>
  <%= link_to "Back to payroll calendars", payroll_calendars_path %>
</div>

app/views/payroll_calendars/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @payroll_calendar %>

<div>
  <%= link_to "Edit this payroll calendar", edit_payroll_calendar_path(@payroll_calendar) %> |
  <%= link_to "Back to payroll calendars", payroll_calendars_path %>

  <%= button_to "Destroy this payroll calendar", @payroll_calendar, method: :delete %>
</div>