config/routes.rb
Rails.application.routes.draw do
  resources :pay_durations do
    member do
      put :position
    end
  end
  resources :payroll_calendars
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  
  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/pay_duration.rb
class PayDuration < ApplicationRecord
  acts_as_list scope: :payroll_calendar, top_of_list: 0
  belongs_to :payroll_calendar
  validates_associated :payroll_calendar
  
  qualifiers = %i(the_first the_second the_third the_fourth the_fifth the_last start_of end_of on)
  Qualifiers = qualifiers.zip(qualifiers.map(&:to_s)).to_h

  Days = (1..31).map { |x| x.to_s.to_sym }
  WeekDays = %i(monday tuesday wednesday thursday friday saturday sunday)
  Endings = (Days + WeekDays + %i(week month)).then { |endings| endings.zip(endings.map(&:to_s)).to_h }

  enum :qualifier, Qualifiers, validate: { allow_blank: false, allow_nil: false }
  enum :ending, Endings, validate: { allow_nil: false, allow_blank: false }

  before_validation do |record|
    record.ending = record.ending.to_s.downcase if record.ending
  end

  def self.named_day_date(index, day_name, month_from: nil, before: nil, after: nil)
    month_from ||= after && after + 1.day || before && before - 1.day || Date.today
    month = (month_from.beginning_of_month..month_from.end_of_month)
    day_name = day_name.to_sym
    count = index_from(index)
    if count >= 0
      count += 1
      date = month.begin - 1.day
      count.times { date = date.next_occurring(day_name) }
    else
      count *= -1
      date = month.end + 1.day
      count.times { date = date.prev_occurring(day_name) }
    end
    date = date.clamp(month)

    if after && date <= after
      named_day_date(index, day_name, month_from: after.next_month, after: after)
    elsif before && date >= before
      named_day_date(index, day_name, month_from: before.prev_month, before: before)
    else
      date
    end

  end

  def self.next_named_day_date(index, day_name, after: nil)
    named_day_date(index, day_name, after: after)
  end

  def self.prev_named_day_date(index, day_name, before: nil)
    named_day_date(index, day_name, before: before)
  end

  def self.day_date(day_number, month_from: nil, before: nil, after: nil)
    month_from ||= after && after + 1.day || before && before - 1.day || Date.today
    month = (month_from.beginning_of_month..month_from.end_of_month)
    date = month.begin + (day_number.to_s.to_i - 1)
    date = date.clamp(month)

    if after && date <= after
      day_date(day_number, month_from: after.next_month, after: after)
    elsif before && date >= before
      day_date(day_number, month_from: before.prev_month, before: before)
    else
      date
    end
  end

  def self.next_day_date(day_number, after: nil)
    day_date(day_number, after: after)
  end

  def self.prev_day_date(day_number, before: nil)
    day_date(day_number, before: before)
  end
  
  def self.end_week_date(index, month_from: nil, before: nil, after: nil)
    month_from ||= after && after + 1.day || before && before - 1.day || Date.today
    month = (month_from.beginning_of_month..month_from.end_of_month)
    index = index_from(index)
    if index >= 0
      date = month.begin
      index.times { date = date.next_week }
    else
      date = month.end
      index *= -1
      index -= 1
      index.times { date = date.prev_week }
    end
    date = date.end_of_week.clamp(month)

    if after && date <= after
      end_week_date(index, month_from: after.next_month, after: after)
    elsif before && date >= before
      end_week_date(index, month_from: before.prev_month, before: before)
    else
      date
    end

  end

  def self.next_end_week_date(index, after: Date.today)
    end_week_date(index, month_from: after, after: after)
  end

  def self.prev_end_week_date(index, before: Date.today)
    end_week_date(index, month_from: before, before: before)
  end
  
  def self.end_month_date(index, month_from: nil, before: nil, after: nil)
    month_from ||= after && after + 1.day || before && before - 1.day || Date.today
    month = (month_from.beginning_of_month..month_from.end_of_month)
    index = index_from(index)
    if index >= 0
      date = month.begin
      index.times { date = date.next_month }
    else
      date = month.end
      index *= -1
      index -= 1
      index.times { date = date.prev_month }
    end
    date = date.end_of_month.clamp(month)

    if after && date <= after
      end_month_date(index, month_from: after.next_month, after: after)
    elsif before && date >= before
      end_month_date(index, month_from: before.prev_month, before: before)
    else
      date
    end

  end

  def self.next_end_month_date(index, after: Date.today)
    end_month_date(index, month_from: after, after: after)
  end

  def self.prev_end_month_date(index, before: Date.today)
    end_month_date(index, month_from: before, before: before)
  end

  def self.index_from(index)
    index.is_a?(Integer) ? index : {first: 0, second: 1, third: 2, fourth: 3, fifth: 4, last: -1, on: 0}[index.to_s.split('_').last&.to_sym].to_i
  end
  
  def range(after: nil)
    after ||= payroll_calendar.starts_on - 1.day
    start = after + 1.day
    if day_of_week?
      (start..self.class.next_named_day_date(qualifier, ending, after: after))
    elsif week?
      (start..self.class.next_end_week_date(qualifier, after: after))
    elsif month?
      (start..self.class.next_end_month_date(qualifier, after: after))
    elsif day?
      (start..self.class.next_day_date(ending, after: after))
    else
      raise "Unidentified pay period #{qualifier} #{ending} not handled. Do something better than raise an error."
    end
  end
  
  def day_of_week?
    WeekDays.include?(ending.to_sym)
  end

  def day?
    Days.include?(ending.to_s.to_i.to_s.to_sym)
  end

end

app/controllers/pay_durations_controller.rb
class PayDurationsController < ApplicationController
  before_action :set_pay_duration, only: %i[ show edit update destroy position ]

  # GET /pay_durations or /pay_durations.json
  def index
    @pay_durations = PayDuration.all.order(position: :asc)
  end

  # GET /pay_durations/1 or /pay_durations/1.json
  def show
  end

  # GET /pay_durations/new
  def new
    @pay_duration = PayrollCalendar.first.pay_durations.new
  end

  # GET /pay_durations/1/edit
  def edit
    respond_to do |format|
      # format.turbo_stream {  render turbo_stream: turbo_stream.remove("#{helpers.dom_id(@pay_duration)}") }
      format.turbo_stream
      format.html
    end
  end

  # POST /pay_durations or /pay_durations.json
  def create
    @pay_duration = PayrollCalendar.first.pay_durations.new(pay_duration_params)

    puts "Create pay period"
    respond_to do |format|
      if @pay_duration.save
        format.turbo_stream
        format.html { redirect_to pay_duration_url(@pay_duration), notice: "Pay period was successfully created." }
        format.json { render :show, status: :created, location: @pay_duration }
      else
        format.turbo_stream { render turbo_stream: turbo_stream.replace("#{helpers.dom_id(@pay_duration)}_form", partial: "form", locals: { pay_duration: @pay_duration }) }
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @pay_duration.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /pay_durations/1 or /pay_durations/1.json
  def update
    respond_to do |format|
      if @pay_duration.update(pay_duration_params)
        format.turbo_stream {
          render :update
        }
        format.html { redirect_to pay_duration_url(@pay_duration), notice: "Pay period was successfully updated." }
        format.json { render :show, status: :ok, location: @pay_duration }
      else
        format.turbo_stream { render turbo_stream: turbo_stream.replace("#{helpers.dom_id(@pay_duration)}_form", partial: "form", locals: { pay_duration: @pay_duration }) }
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @pay_duration.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /pay_durations/1 or /pay_durations/1.json
  def destroy
    @pay_duration.destroy!

    respond_to do |format|
      format.turbo_stream
      format.html { redirect_to pay_durations_url, notice: "Pay period was successfully destroyed." }
      format.json { head :no_content }
    end
  end
  
  def position
    @pay_duration.insert_at(params[:position].to_i)

    render turbo_stream:
             turbo_stream.replace("#pay_periods",
                                  partial: "list",
                                  locals: { payroll_calendar: @pay_duration.payroll_calendar })
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_pay_duration
      @pay_duration = PayDuration.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def pay_duration_params
      params.require(:pay_duration).permit(:ending, :qualifier, :position, :payroll_calendar_id)
    end
end

app/helpers/pay_durations_helper.rb
module PayDurationsHelper
  
  def qualifier(pay_duration = assigns['pay_duration'])
    if pay_duration.respond_to?(:qualifier)
      pay_duration.qualifier.to_s.sub('the_','').humanize
    else
      ''
    end
  end
  
  def ending(pay_duration = assigns['pay_duration'])
    if pay_duration.respond_to?(:ending)
      pay_duration.ending.to_s.humanize
    else
      ''
    end
  end

end

app/views/pay_durations/_form.html.erb
<%= form_with(model: pay_duration, id: "#{dom_id(pay_duration)}_form", class: :pay_duration_form, data: { controller: 'pay-duration' }) do |form| %>
  <% if pay_duration.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(pay_duration.errors.count, "error") %> prohibited this pay_duration from being saved:</h2>
      <ul>
        <% pay_duration.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :qualifier %>
    <%= form.select :qualifier, 
                    options_for_select(PayDuration::Qualifiers.transform_keys { |x| x.to_s.sub('the_', '').humanize }, pay_duration.qualifier),
                    {}, { data: { action: 'pay-duration#updateEndings', pay_duration_target: :qualifier } } %>
  </div>

  <div>
    <%= form.label :ending %>
    <%= form.text_field :ending, list: 'endings', value: ending %>
    <%= content_tag(:datalist, nil, id: :endings) do %>
      <% PayDuration::Endings.keys.reject { |x| x =~ /\d+/ }.each do |ending| %>
        <%= content_tag(:option, nil, value: ending.to_s.humanize, data: { pay_duration_target: ending.ends_with?('day' ) ? :day : ending }) %>
      <% end %>
    <% end %>
  </div>

  <div>
    <%= form.label :position %>
    <%= form.number_field :position, type: "hidden" %>
  </div>

  <div>
    <%= form.label :payroll_calendar_id %>
    <%= form.text_field :payroll_calendar_id, type: "hidden" %>
  </div>

  <div>
    <%= form.submit pay_duration.new_record? ? 'Add' : 'Save' %>
    <% unless pay_duration.new_record? %>
      <%= link_to "Cancel", pay_durations_path %>
    <% end %>
  </div>
<% end %>

app/views/pay_durations/_list.html.erb
<ol id="#pay_periods">
  <% (payroll_calendar&.payroll_periods || []).each do |date_range| %>
  <li <%= date_range.include?(Date.today) ? "id=current_pay_period" : ''  %>>
    <%= date_range.begin.strftime("%B %d, %Y") + ' to ' + date_range.end.strftime("%B %d, %Y") %> 
  </li>
  <% end %>
</ol>

app/views/pay_durations/_pay_duration.html.erb
<%= turbo_frame_tag dom_id(pay_duration), data: { sortable_url: position_pay_duration_path(pay_duration) } do %>
  <div class="pay_duration" data-sortable-handle>
      <p class="pay_duration_qualifier">
        <strong>Qualifier:</strong>
        <%= qualifier %>
      </p>
  
      <p class="pay_duration_ending">
        <strong>Ending:</strong>
        <%= ending %>
      </p>
  
      <p class="pay_duration_position">
        <strong>Position:</strong>
        <%= pay_duration.position %>
      </p>
  
      <p class="pay_duration_payroll_calendar">
        <strong>Payroll calendar:</strong>
        <%= pay_duration.payroll_calendar_id %>
      </p>
      <%= link_to edit_pay_duration_path(pay_duration), data: {turbo_stream: true} do %>
          <%= inline_svg_tag("edit.svg", class: 'edit_pay_duration_icon') %>
      <% end %>
      <%= link_to pay_duration, data: { turbo_method: :delete } do %>
        <%= inline_svg_tag("trash.svg", class: 'delete_pay_duration_icon') %>
      <% end %>
  </div>
<% end %>

app/views/pay_durations/create.turbo_stream.erb
<%= turbo_stream.append "pay_durations" do %>
  <%= render "pay_duration", pay_duration: @pay_duration %>
<% end %>
<%= turbo_stream.replace "#{dom_id(PayrollCalendar.first.pay_durations.new)}_form" do %>
  <%= render "form", pay_duration: PayrollCalendar.first.pay_durations.new %>
<% end %>
<%= turbo_stream.replace "#pay_periods" do %>
  <%= render 'list', payroll_calendar: @pay_duration.payroll_calendar %>
<% end %>

app/views/pay_durations/destroy.turbo_stream.erb
<%= turbo_stream.remove("#{dom_id(@pay_duration)}") %>
<%= turbo_stream.replace "#pay_periods" do %>
  <%= render 'list', payroll_calendar: @pay_duration.payroll_calendar %>
<% end %>

app/views/pay_durations/edit.html.erb
<h1>Editing pay period</h1>
<%= turbo_frame_tag dom_id(@pay_duration) do %>
  <%= render "form", pay_duration: @pay_duration %>
<% end  %>
<br>

<div>
  <%= link_to "Show this pay period", @pay_duration %> |
  <%= link_to "Back to pay periods", pay_durations_path %>
</div>

app/views/pay_durations/edit.turbo_stream.erb
<%= turbo_stream.replace dom_id(@pay_duration) do %>
  <%= render "form", pay_duration: @pay_duration %>
<% end  %>

app/views/pay_durations/index.html.erb
<div id="pay_period_display">
  <div>
    <p style="color: green"><%= notice %></p>
    
    <h1>Pay Periods</h1>
    
    <p>Ends On</p>
    <div id="pay_durations" data-controller="sortable" data-sortable-resource-name-value="pay_duration">
      <% @pay_durations.each do |pay_duration| %>
        <% assigns['pay_duration'] = pay_duration %>
        <%= render pay_duration %>
      <% end %>
    </div>
    
    <%= render 'form', pay_duration: PayrollCalendar.first.pay_durations.new %>
  </div>
  <%= render 'list', payroll_calendar: @pay_durations.first&.payroll_calendar %>
</div>

app/views/pay_durations/new.html.erb
<h1>New pay period</h1>

<%= render "form", pay_duration: @pay_duration %>

<br>

<div>
  <%= link_to "Back to pay periods", pay_durations_path %>
</div>

app/views/pay_durations/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @pay_duration %>

<!--
<div>
  <%= link_to "Edit this pay period", edit_pay_duration_path(@pay_duration) %> |
  <%= link_to "Back to pay periods", pay_durations_path %>

  <%= button_to "Destroy this pay period", @pay_duration, method: :delete %>
</div>
  -->

app/views/pay_durations/update.turbo_stream.erb
<%= turbo_stream.replace "#{dom_id(@pay_duration)}_form" do %>
  <%= render @pay_duration %>
<% end  %>
<%= turbo_stream.replace "#{dom_id(PayrollCalendar.first.pay_durations.new)}_form" do %>
  <%= render "form", pay_duration: PayrollCalendar.first.pay_durations.new %>
<% end %>
<%= turbo_stream.replace "#pay_periods" do %>
  <%= render 'list', payroll_calendar: @pay_duration.payroll_calendar %>
<% end %>